version: '3'

services:
  db:
    image: mysql:8.0.27
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
    volumes:
      - twitterdb:/var/lib/mysql

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    restart: always
    environment:
      DEBUG: $DEBUG
      ALLOWED_HOSTS: $ALLOWED_HOSTS
      SECRET_KEY: $SECRET_KEY
      REFRESH_TOKEN_SECRET: $REFRESH_TOKEN_SECRET
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_HOST: $DB_HOST
      CORS_ALLOW_CREDENTIALS: $CORS_ALLOW_CREDENTIALS
      CORS_ORIGIN_WHITELIST: $CORS_ORIGIN_WHITELIST
    depends_on:
      - db

volumes:
  twitterdb:
