# Generated by Django 3.2.11 on 2022-01-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hummers', '0003_tweet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={},
        ),
    ]
